Add goldens for egress rule tests
istio/pilot pull request #1249
Opened 2017-09-12 14:33 UTC by rshriram

**What this PR does / why we need it**:
Improving test coverage for egress rules. Built on top of previous PR.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Contributes to #1232 
**Special notes for your reviewer**:

**Release note**:

```release-note
```

2017-09-12 20:08 UTC, GregHanson approved these changes
lgtm

2017-09-12 20:08 UTC, kyessenov requested changes

2017-09-12 20:08 UTC, kyessenov commented on proxy/envoy/discovery_test.go
> +	addConfig(registry, egressRule, t)
please remove egressRule from common setup. The tests should test each rule/config in isolation.

2017-09-12 20:17 UTC, istio-testing commented
@rshriram: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
prow/pilot-e2e-smoketest.sh | 672176386f1e0d7651dcd7d3a54926baea802b5a | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1249/pilot-e2e-smoketest/365/) | `/test pilot-e2e-smoketest`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-09-12 21:05 UTC, istio-testing commented
@rshriram: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
prow/pilot-e2e-smoketest.sh | 672176386f1e0d7651dcd7d3a54926baea802b5a | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1249/pilot-e2e-smoketest/365/) | `/test pilot-e2e-smoketest`
prow/pilot-presubmit.sh | 19bf87aa703a5ef2e3826c6323081f95c726537d | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1249/pilot-presubmit/1063/) | `/test pilot-presubmit`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-09-12 21:37 UTC, istio-testing commented
@rshriram: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
prow/pilot-e2e-smoketest.sh | 672176386f1e0d7651dcd7d3a54926baea802b5a | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1249/pilot-e2e-smoketest/365/) | `/test pilot-e2e-smoketest`
prow/pilot-presubmit.sh | a874116978802ee14c16c2461deea73debef6183 | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1249/pilot-presubmit/1067/) | `/test pilot-presubmit`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-09-12 22:13 UTC, kyessenov approved these changes

2017-09-12 22:30 UTC, istio-testing commented
@rshriram: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
prow/pilot-presubmit.sh | 071097901b4f107867682c3a469ab056487aace7 | [link](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_pilot/1249/pilot-presubmit/1073/) | `/test pilot-presubmit`



<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>
<!-- test report -->

2017-09-12 23:14 UTC, merged

2017-09-12 23:14 UTC, rshriram commented
One at a time wins again!

2018-05-16 15:53 UTC, Arttii commented
@rshriram So I after going from a bunch of issues I stumbled here concerning the headless service auth. I was wondering why was it disabled, I cannot find anywhere why exactly is it like this. Is it a perf problem or something?

2018-06-02 03:46 UTC, ldemailly commented
not a perf problem